Fix build of the distTar/distZip as the same content was added multiple time in the distribution file.
Unzip the files would lead to the error:

error: invalid zip file with overlapped components (possible zip bomb)